### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by aritjahja** [libsndfile/libsndfile#626] opened 2020-10-08 06:25 UTC
macOS 10.11 El Capitan
libsndfile-1.0.30.tar.bz2
Error: SHA256 mismatch
Expected: ec898634766595438142c76cf3bdd46b77305d4a295dd16b29d024122d7a4b3f
  Actual: 9df273302c4fa160567f412e10cc4f76666b66281e7ba48370fb544e87e4611a

I have already tried to download it using a download manager. The problem won't get away.

**Comment by evpobr** [comment] 2020-10-08 06:31
Thanks for report. I'll check it out.

**Comment by evpobr** [comment] 2020-10-08 06:36
More info please. How do you check hash?

**Comment by evpobr** [comment] 2020-10-08 06:38
> Expected: ec898634766595438142c76cf3bdd46b77305d4a295dd16b29d024122d7a4b3f

Where did this come from?

**Comment by aritjahja** [comment] 2020-10-08 06:38
I was trying to install ffmpeg usin homebrew.

**Comment by evpobr** [comment] 2020-10-08 06:55
This must have happened because we uploaded the file again. They need to update the formula. Raise issue [there](https://github.com/Homebrew/homebrew-core).

I'll add a note to the release page.

**Comment by aritjahja** [comment] 2020-10-08 07:30
I've post the issue. You can find it [here](https://github.com/Homebrew/homebrew-core/issues/62524).

**Comment by fxcoudert** [comment] 2020-10-08 07:43
Please consider releasing a new version (update minor or patch version number) if you release a different file.

**Comment by evpobr** [comment] 2020-10-09 03:41
The problem is Windows line endings of some autogenerated scripts in tarball. No source changes at all.

**Comment by cocode** [comment] 2020-10-09 20:36
Right, but programs store checksums for versions, and this will break things like brew, maven, etc. I'll second fxcoudert's comment: *ANY* change needs a new version. 

Thanks.

**Comment by njh** [comment] 2020-10-09 21:11
I agree - any change to the source files should be a new release with a new version number. But maybe with a with a different build number? (as described on https://semver.org/)

But wasn't changing the line ending a bug fix anyway?

**Comment by evpobr** [comment] 2020-10-12 05:36
@SoapGentoo , what do think?

**Comment by SoapGentoo** [comment] 2020-10-12 13:22
While I get the sentiment, doing a new release involves a whole barrage of updates, for something that involves an incorrectly generated tarball. Nothing in git actually changed. Hence we skipped it.

**Comment by gord288** [comment] 2020-10-12 14:02
Okay so what can folks like myself and @aritjahja do to work around this mismatch issue? I am also trying to update a homebrew formula that has libsndfile as a dependency.

**Comment by evpobr** [comment] 2020-10-12 15:32
> Okay so what can folks like myself and @aritjahja do to work around this mismatch issue? I am also trying to update a homebrew formula that has libsndfile as a dependency.

I'm not sure why they closed @aritjahja's issue Homebrew/homebrew-core#62524, probably contributing guidlines violation, but i asked for help @jnozsc, who made previous fomula.

**Comment by fxcoudert** [comment] 2020-10-12 16:05
I've opened a PR: https://github.com/Homebrew/homebrew-core/pull/62754
Homebrew is very careful with checksum changes, as they could be due to malicious activity.

**Comment by aritjahja** [comment] 2020-10-13 02:22
> > Okay so what can folks like myself and @aritjahja do to work around this mismatch issue? I am also trying to update a homebrew formula that has libsndfile as a dependency.
> 
> I'm not sure why they closed @aritjahja's issue [Homebrew/homebrew-core#62524](https://github.com/Homebrew/homebrew-core/issues/62524), probably contributing guidlines violation, but i asked for help @jnozsc, who made previous fomula.

Perhaps we have to install it manually uing configure and make commands? The problem is, if those are all we should do, I don't know how to do it.

**Comment by evpobr** [comment] 2020-10-13 04:18
@aritjahja,  it is fixed in Homebrew, thanks to @fxcoudert.

**Comment by aritjahja** [comment] 2020-10-13 04:19
Thank you for the information @evpobr. And thank you for the fix @fxcoudert.

**Closed** 2020-10-13 04:36 UTC
Labels: wontfix
