### ISSUE TITLE
OGG out-of-range clipping

### ISSUE THREAD

**Issue by RobertBColton** [libsndfile/libsndfile#672] opened 2020-12-13 13:29 UTC
I am forwarding this issue I originally posted on OpenAL soft.
https://github.com/kcat/openal-soft/issues/505

It's causing issues for a user of our game engine.
https://github.com/enigma-dev/enigma-dev/issues/2140

This specific OGG audio file they have is not playing correctly after being decoded by libsndfile through Alure. On Windows, I get static noise, where the user on Linux hears clipping. If any devs here would test it and see if this is a libsndfile issue, we would really appreciate it! 👍

**Comment by makitsune** [comment] 2020-12-31 21:23
I just came across this issue myself today.

**Comment by arthurt** [comment] 2021-01-08 00:45
> The OggVorbis file in this issue contains sample data over 0db. I see a peak sample value of 2.4 (3db ish).
>
> It is the explicit behaviour of libsndfile that when reading sample data as an integer type that 0db is mapped to the maximum representation of that integer type. If the audio data is being read as ints or shorts, this is not a bug, it is an explicit behaviour. The audio is clipped because the input file contains out-of-range data.
>
>Note that it is possible to encode >0db signals in Vorbis, but that it is not able to store arbitrary signal ranges. After about 13db the reference Vorbis encoder stops making sense of the input.
>
>To play back this audio correctly, it needs to be normalized. Libsndfile includes commands to find the signal max in a file, so that callers can normalize the audio. To read samples greater than 0db, read the data as float or double.
>
>Admittedly, libsndfile does have an issue with how it reports signal max varying over different supported codecs.

**Comment by arthurt** [comment] 2021-01-08 01:01
Duplicate of [194](194)

**Closed by arthurt** 2021-01-08 01:01 UTC
Labels: duplicate, help wanted
