### ISSUE TITLE
Mp3 not supported with version 1.1.0-2 in Arch Linux official repository

### ISSUE THREAD

**Issue by jack1223233244** [libsndfile/libsndfile#839] opened 2022-05-27 21:25 UTC
Mp3 is not listed among the supported formats when checking with `SFC_GET_FORMAT_MAJOR_COUNT`.

Using version 1.1.0-2 from Arch Linux official repository.

**Comment by evpobr** [comment] 2022-05-28 04:11
Hi @jack1223233244 , thanks for report.

Duplicate of #837 .

**Closed by evpobr** 2022-05-28 04:11 UTC
