### ISSUE TITLE
Add FindMpg123.cmake to the 1.1.0 release

### ISSUE THREAD

**Issue by sakertooth** [libsndfile/libsndfile#838] opened 2022-05-20 13:54 UTC
The 1.1.0 tar release does not include FindMpg123.cmake, which, when used to build, does not support MPEG. The source code in the release does include it however, but not the tar.

Arch (and likely other distros) use the tar release, so the build will optionally skip on MPEG support since it could not find the Mpg123 library.

The win32 and win64 releases might be affected as well.

**Comment by sakertooth** [comment] 2022-05-20 14:04
Seems like the beta versions of 1.1.0 does include FindMpg123.cmake, so I guess it has to wait until the next stable release.

**Comment by evpobr** [comment] 2022-05-22 04:27
Duplicate of #816

**Closed by evpobr** 2022-05-22 04:27 UTC
